version: "3.8"
services:
  backend:
    build: .
    image: project_management_express_backend
    container_name: express-backend
    ports:
      - "5000:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
